owner: abelfodil
repo: upptime-belfodil.ca

sites:
  - name: argo-cd-argocd-server
    url: https://argo.belfodil.ca
    expectedStatusCodes:
      - 403
  - name: authentik
    url: https://auth.belfodil.ca
  - name: archivebox
    url: https://archive.belfodil.ca
  - name: bazarr
    url: https://bazarr.belfodil.ca
  - name: epicgames-freegames
    expectedStatusCodes:
      - 502
    url: https://epicgames-freegames.belfodil.ca
  - name: filebrowser
    url: https://filebrowser.belfodil.ca
  - name: gotify
    url: https://gotify.belfodil.ca
  - name: grafana
    url: https://grafana.belfodil.ca
    expectedStatusCodes:
      - 403
  - name: home-assistant
    url: https://ha.belfodil.ca
  - name: homer-operator
    url: https://dash.belfodil.ca
  - name: immich
    url: https://immich.belfodil.ca
  - name: inventree
    url: https://inventree.belfodil.ca
  - name: jellyfin
    url: https://jellyfin.belfodil.ca
  - name: jellyseerr
    url: https://jellyseerr.belfodil.ca
  - name: kubernetes-dashboard
    url: https://kubernetes.belfodil.ca
    expectedStatusCodes:
      - 403
  - name: lazylibrarian
    url: https://lib.belfodil.ca
  - name: miniflux
    url: https://miniflux.belfodil.ca
  - name: minio
    url: https://minio.belfodil.ca
  - name: netbox
    url: https://netbox.belfodil.ca
  - name: nextcloud
    url: https://nextcloud.belfodil.ca
  - name: nodemation
    url: https://n8n.belfodil.ca
  - name: obico-server
    url: https://obico.belfodil.ca
  - name: octoprint
    url: https://octoprint.belfodil.ca
  - name: octoprint-webcam
    url: https://octoprint-webcam.belfodil.ca
    expectedStatusCodes:
      - 401
  - name: pgadmin4
    url: https://pgadmin4.belfodil.ca
    expectedStatusCodes:
      - 403
  - name: prowlarr
    url: https://prowlarr.belfodil.ca
  - name: radarr
    url: https://radarr.belfodil.ca
  - name: redis-insight
    url: https://redis.belfodil.ca
    expectedStatusCodes:
      - 403
  - name: sonarr
    url: https://sonarr.belfodil.ca
  - name: tdarr
    url: https://tdarr.belfodil.ca
  - name: transmission
    url: https://transmission.belfodil.ca
    expectedStatusCodes:
      - 401
  - name: traefik-dashboard
    url: https://traefik.belfodil.ca
    expectedStatusCodes:
      - 403
  - name: Minecraft Bedrock
    url: https://api.mcsrvstat.us/bedrock/simple/home.belfodil.ca:30778
  - name: wakapi
    url: https://wakapi.belfodil.ca

status-website:
  baseUrl: upptime-belfodil.ca
  theme: dark
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime for belfodil.ca
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Uptime page for belfodil.ca
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
